os: osx
osx_image: xcode12
language: objective-c
before_script:
  - pod lib lint
matrix:
  include:
    - env: NAME=Xcode DESTINATION="platform=iOS Simulator,name=iPhone 11"
script:
  - xcodebuild test -project EventBottle.xcodeproj -scheme EventBottle -destination "${DESTINATION}"
